// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color palette settings for cell state representations.
 */
export type ColorPalette = { 
/**
 * Classic/Mono-color alive cell color [r, g, b]
 */
classic: [number, number, number], 
/**
 * Bi-state colors: [alive, born, dying] each as [r, g, b]
 */
bi_state: [[number, number, number], [number, number, number], [number, number, number]], 
/**
 * Tri-state colors: states 1 through 7 each as [r, g, b]
 */
tri_state: [[number, number, number], [number, number, number], [number, number, number], [number, number, number], [number, number, number], [number, number, number], [number, number, number]], };
