// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a request from the client.
 */
export type PatternInfo = { name: string, description: string, rle: string, };
