// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a request from a client to the simulation server.
 */
export type Request = { "type": "NextStep" } | { "type": "Reset" } | { "type": "Start" } | { "type": "Stop" } | { "type": "Seed", "payload": string } | { "type": "Shutdown" } | { "type": "HandshakeMetricsOnly" } | { "type": "HandshakeFullSnapshot", "payload": { viewport: [[bigint, bigint], [bigint, bigint]] | null, } } | { "type": "AckPreviousFrame", "payload": { viewport: [[bigint, bigint], [bigint, bigint]] | null, } } | { "type": "UpdateViewport", "payload": { viewport: [[bigint, bigint], [bigint, bigint]], } };
