// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a request from a client to the simulation server.
 */
export type Request = { "type": "NextStep" } | { "type": "Reset" } | { "type": "GetState", "payload": { generation: bigint, viewport: [[bigint, bigint], [bigint, bigint]] | null, } } | { "type": "Start" } | { "type": "Stop" } | { "type": "Seed", "payload": string } | { "type": "Shutdown" };
