// Copyright (C) 2026 Steven P. Collins. All rights reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternInfo } from "./PatternInfo";
import type { Telemetry } from "./Telemetry";

/**
 * Represents a response from the simulation server to a client.
 */
export type Response = { "type": "Ok" } | { "type": "SnapshotAvailable", "payload": { telemetry: Telemetry, } } | { "type": "Error", "payload": string } | { "type": "Welcome", "payload": { cores: number, patterns: Array<PatternInfo>, } } | { "type": "BinaryStateHeader", "payload": { generation: bigint, record_count: bigint, } };
