// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared telemetry metrics for all interfaces.
 */
export type Telemetry = { generation: bigint, population: bigint, is_running: boolean, gps: number, work_rate: number, net_rate: number, bounds: [[bigint, bigint], [bigint, bigint]] | null, };
