[package]
name = "rustylife-server"
version = "0.1.0"
edition = "2024"

[dependencies]
rustylife-core = { path = "../rustylife-core" }
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.7", features = ["ws"] }
anyhow = "1.0"
egui = "0.28"
eframe = "0.28"
crc32fast = "1.5.0"
# Removed interprocess

[dev-dependencies]
tempfile = "3.3"
